config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => 'sessions#auth_failure'

  delete 'logout' => 'sessions#destroy'
  delete 'logout' => 'sessions#destroy'
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/graduating_class.rb
# == Schema Information
#
# Table name: graduating_classes
#
#  id               :integer          not null, primary key
#  graduating_class :string(255)      not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class GraduatingClass < ApplicationRecord
  
  has_many :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  graduating_class_id :integer
#  provider            :string(255)      not null
#  uid                 :string(255)      not null
#  name                :string(255)      not null
#  email               :string(255)
#  gender              :integer
#  image_url           :string(255)
#  birthplace          :integer
#  industry            :string(255)
#  company             :string(255)
#  useful_things       :text(65535)
#  note                :text(65535)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
# Indexes
#
#  index_users_on_graduating_class_id  (graduating_class_id)
#  index_users_on_provider_and_uid     (provider,uid) UNIQUE
#

class User < ApplicationRecord
  belongs_to :graduating_class, optional: true

  prefectures = {
    Hokkaido: 1, Aomori: 2, Iwate: 3, Miyagi: 4, Akita: 5, Yamagata: 6, Fukushima: 7,
    Ibaraki: 8, Tochigi: 9, Gunma: 10, Saitama: 11, Chiba: 12, Tokyo: 13, Kanagawa: 14, Niigata: 15,
    Toyama: 16, Ishikawa: 17, Fukui: 18, Yamanashi: 19, Nagano: 20, Gifu: 21, Shizuoka: 22, Aichi: 23,
    Mie: 24, Shiga: 25, Kyoto: 26, Osaka: 27, Hyogo: 28, Nara: 29, Wakayama: 30, Tottori: 31, Shimane: 32,
    Okayama: 33, Hiroshima: 34, Yamaguchi: 35, Tokushima: 36, Kagawa: 37, Ehime: 38, Kochi: 39, Fukuoka: 40, Saga: 41,
    Nagasaki: 42, Kumamoto: 43, Oita: 44, Miyazaki: 45, Kagoshima: 46, Okinawa: 47
  }

  enum gender: [:male, :female, :other]
  enum birthplace: prefectures

  validates :gender, presence: true, on: :update
  validates :useful_things, length: {maximum: 500}, presence: true, on: :update
  validates :note, length: { maximum: 500 }, presence: true, on: :update
  validates :graduating_class, presence: true, on: :updae

  scope :get_by_graduating_class, -> (graduating_class_id) { where(graduating_class_id: graduating_class_id) }

  def self.find_orcreate_from_auth_hash(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    name = auth_hash[:info][:name]
    email = auth_hash[:info][:email]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = name
      user.email = email
      user.image_url = image_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_orcreate_from_auth_hash(request.env['omniauth.auth'])
    session[:user_id] = user.id

    if user.useful_things? || user.note?
      redirect_to root_path, notice: 'ログインしました'
    else
      redirect_to edit_user_path(user), notice: 'ログインしました'
    end
  end

  def destroy
    logout if logged_in?
    redirect_to  root_path, notice: 'ログアウトしました'
  end

  def auth_failure
    render :status => 500
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    if params[:graduating_class_id].present?
      @graduating_class = GraduatingClass.find(params[:graduating_class_id])
      @graduating_class_users = @users.get_by_graduating_class params[:graduating_class_id]
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user, notice: '更新しました'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:graduating_class_id, :gender, :birthplace, :industry, :company, :useful_things, :note)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def curent_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    cookies.delete(:user_id)
  end

  def logout
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header clss="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'OB&OG MATCHER', root_path, class: 'navbar-brand' %>
      <% if logged_in? %>
        <button type="button" class="navbar-toggle cllapsed" data-toggle="collapse" data-target="#header-navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      <% end %>
    </div>
    <% if logged_in? %>
    <div class="collapse navbar-collapse" id="header-navbar" role='navigation'>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "#{current_user.name}", current_user, class: 'head-link' %></li>
        <li><%= link_to "Mゼミ一覧", users_path, class: 'head-link' %></li>
        <li><%= link_to "Log out",  logout_path, method: "delete", class: 'head-link' %></li>
      </ul>
    </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>ObOgMatcher</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag('/favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<section class="home-main">
  <div class="main-mess">
    <h3>I ♥ Mゼミ</h3>
    <p>北海道での出会いを大切に。。。</p>
  </div>
  <% if logged_in? %>
    <div class="logout-bt">
      <%= link_to "Log out",  logout_path, method: "delete", class: 'btn btn-primary col-md-4 ' %>
    </div>
  <% else %>
    <div class="login-bt">
      <%= link_to 'facebookでログイン', '/auth/facebook', class: 'btn btn-primary col-md-4' %>
    </div>
  <% end %>
</section>
<section class="home-mess">
  <div class="mess-class">
    <div class="mess col-md-4 col-xs-12">
      <span class="glyphicon glyphicon-user"></span>
      <p>
        今まで以上に円滑な交流が出来るようになる。
        先輩方のバックグラウンドを見て話してみたいなどあれば、直接アプローチをしてみよう。
        <br>この繋がりを上手に利用し合うことができる。
      </p>
    </div>
    <div class="mess col-md-4 col-xs-12">
      <span class="glyphicon glyphicon-warning-sign"></span>
      <p>
        困った時は助け合い。例えば、就活どうしたらいい？という時は先輩からアドバイスをもらおう。
        また、こんな業界興味あるけどどうしたらいいかわからない。そんな時は、先輩方に聞くのが一番。
      </p>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<session class="edit-user">
<div class="page-header">
  <h1>Please edit your user information</h1>

  <p>
    このウェブサービスは、MゼミのOB&OGが円滑に交流ができるようにと考えています<br>
    また、MゼミOB&OGの中で、就活や転職、ビジネスの場で "<%= @user.name %>さん" を必要としている人がいます<br>
    ですので、より正確な "<%= @user.name %>さん" の情報が必要です
  </p>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h2>Your information</h2>
  </div>
  <div class="panel-body">
    <div class="panel col-md-6 col-md-offset-3">
      <div class="main-panel">
        <div class="user-picture col-md-2">
          <%= image_tag @user.image_url %>
        </div>
        <div class="user-name col-md-9 col-md-offset-1">
          <%= @user.name %>
        </div>
      </div>

      <%= form_for(@user, role: 'form') do |f| %>
        <% if @user.errors.any? %>
          <div class="alert alert-danger">
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <h4><%= f.label :性別 %></h4>
          <div>
            <%= f.radio_button :gender, :male, checked: true %> <%= f.label :Male %>
            <%= f.radio_button :gender, :female %> <%= f.label :Female %>
            <%= f.radio_button :gender, :other %> <%= f.label :Other %>
          </div>
          <span class="label label-danger req">必須</span>
        </div>

        <div class="form-group">
          <h4><%= f.label :第何期生 %></h4>
          <%= f.select :graduating_class_id, GraduatingClass.all.map{ |o| [o.graduating_class, o.id]}, {}, class: 'form-control' %>
          <span class="label label-danger req">必須</span>
        </div>

        <div class="form-group">
          <h4><%= f.label :出身地 %></h4>
          <%= f.select :birthplace, User.birthplaces.keys.to_a, {}, class: 'form-control' %>
        </div>

        <div class="form-group">
          <h4><%= f.label :業界 %></h4>
          <%= f.text_field :industry, class: 'form-control', placeholder: 'ex) Web業界' %>
          <p>*学生の場合は『学生』と入力してください</p>

        </div>

        <div class="form-group">
          <h4><%= f.label :お勤め先 %></h4>
          <%= f.text_field :company, class: 'form-control', placeholder: 'ex) 株式会社Mゼミ' %>
          <p>*学生の場合は『学生』と入力してください</p>
        </div>

        <div class="form-group">
          <h4><%= f.label :あなたが力になれる事 %><span id="count-useful-things"></span></h4>
          <%= f.text_area :useful_things, rows: 10, class: 'form-control useful-things-textarea', placeholder:'ex) web業界についての相談を受けることができます。 ' %>
          <span class="label label-danger req">必須</span>
        </div>

        <div class="form-group">
          <h4><%= f.label :あなたをより詳しく %><span id="count-note"></span></h4>
          <%= f.text_area :note, maxlength: 500, rows: 10, class: 'form-control note-textarea', placeholder: 'ex) 趣味：読書、旅行' %>
          <span class="label label-danger req">必須</span>
        </div>

          <div class="form-group">
            <%= f.submit 'Submit', maxlength: 500, class: 'btn btn-default', data: { distable_with: '更新中...'} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</session>

app/views/users/index.html.erb
<section class="users">
  <div class="panel panel-default">
    <div class="panel-heading graduating-class-index">
      <div class="gc-head col-md-offset-1">
        <h2>Mゼミ一覧</h2>
      </div>
    </div>
    <div class="panel-body">
      <section class="graduating-class" id="gcl">
        <ul>
          <% GraduatingClass.all.map{ |o| [o.graduating_class, o.id] }.each do |index| %>
            <li class="col-md-4 col-xl-12 col-sm-6 graduating-class-list">
              <%= link_to "#{index[0]}", users_path(graduating_class_id: index[1]) %>
            </li>
          <% end %>
        </ul>
      </section>
    </div>
  </div>
</section>

<% if params[:graduating_class_id].present? %>
  <section class="users-list">
    <div class="panel panel-default">
      <div class="panel-heading user-index-title">
        <div class="col-md-offset-1">
          <h2><%= @graduating_class.graduating_class %></h2>
        </div>
      </div>
      <div class="panel-body">
        <% if @graduating_class_users.present? %>
          <% @graduating_class_users.each do |user| %>
            <%= link_to user_path(user), class: 'user-link' do %>
              <div class="panel panel-default">
                <div class="panel-heading user-index">
                  <div class="user-picture user-inf col-sm-3">
                    <%= image_tag user.image_url %>
                  </div>

                  <div class="user-name user-inf col-sm-9">
                    <h3><%= user.name %></h3>
                  </div>

                  <div class="user-gender user-inf col-xs-12 col-sm-6">
                    <h3>性別: <%= user.gender %></h3>
                  </div>

                  <div class="user-birthplace user-inf col-xs-12 col-sm-6">
                    <h3>出身地: <%= user.birthplace %></h3>
                  </div>

                  <div class="user-industry user-inf col-xs-12 col-sm-6">
                    <h3>業界: <%= user.industry %></h3>
                  </div>

                  <div class="user-company user-inf col-xs-12 col-sm-6">
                    <h3>企業: <%= user.company %></h3>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <div class="col-md-offset-1">
            <h3>現在、<%= @graduating_class.graduating_class %>に登録されている方はいません。</h3>
          </div>
        <% end %>
      </div>
    </div>
  </section>
<% end %>

app/views/users/show.html.erb
<div class="page-header">
  <h1>Profile</h1>
</div>
<div class="panel panel-default">
  <div class="panel-heading show-user-inf">
    <div class="user-picture user-inf col-sm-3">
      <%= image_tag @user.image_url %>
    </div>

    <div class="user-name user-inf col-xs-9 col-sm-9 ">
      <h3><%= @user.name %></h3>
    </div>

    <div class="user-gender user-inf col-xs-12 col-sm-6">
      <h3>性別: <%= @user.gender %></h3>
    </div>

    <div class="user-birthplace user-inf col-xs-12 col-sm-6">
      <h3>出身地: <%= @user.birthplace %></h3>
    </div>

    <div class="user-industry user-inf col-xs-12 col-sm-6">
      <h3>業界: <%= @user.industry %></h3>
    </div>

    <div class="user-company user-inf col-xs-12 col-sm-6">
      <h3>企業: <%= @user.company %></h3>
    </div>
  </div>
  <div class="panel-body">
    <div class="panel col-md-6 col-md-offset-3">
      <div class="main-panel user-other-inf">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3>力になれること</h3>
          </div>

          <div class="panel-body">
            <div class="panel">
              <%= simple_format(@user.useful_things) %>
            </div>
          </div>
        </div>
      </div>

      <div class="main-panel">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3>その他の情報</h3>
          </div>

          <div class="panel-body">
            <div class="panel">
              <%= simple_format(@user.note) %>
            </div>
          </div>
        </div>
      </div>

      <% if @user == current_user %>
        <%= link_to 'Edit profile', edit_user_path(current_user), class: 'btn btn-default col-md-12 col-xs-12' %>
      <% end %>
    </div>
  </div>
</div>